[build-system]
requires = ["setuptools>61"]
build-backend = "setuptools.build_meta"

[project]
name = "scatteredvision"
version = "0.1.0"
description = "Scattered Vision facial analysis GUI"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
scatteredvision = "scatteredvision.__main__:main"
